variables:
  BuildConfiguration: 'Release'
  CI: true
  NODE_VERSION: 16.14.2
  DOTNET_VERSION: 6.0.x


trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: 'Frontend'
    pool:
      vmImage: 'ubuntu-20.04'
      demands: azureps
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NODE_VERSION)'
        inputs:
          versionSpec: $(NODE_VERSION)

      - task: 'Bash@3'
        displayName: 'corepack enable'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'corepack enable'

      - task: 'Bash@3'
        displayName: 'pnpm i'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'pnpm i'


      # - task: Docker@2
      #   condition: ne(variables['Build.Reason'], 'PullRequest')
      #   inputs:
      #     containerRegistry: 'eesdev2'
      #     repository: 'eesfrontendcontainer'
      #     command: 'buildAndPush'
      #     Dockerfile: 'docker/Dockerfile.public-frontend'
      #     tags: $(Build.BuildNumber)
      #     arguments: '-f docker/Dockerfile.public-frontend'
      #     buildContext: 
      - task: Docker@2
        displayName: "build public frontend docker image"
        condition: ne(variables['Build.Reason'], 'PullRequest')
        inputs:
          containerRegistry: 'eesdev2'
          repository: 'eesfrontendcontainer'
          command: 'build'
          Dockerfile: 'docker/Dockerfile.public-frontend'
          buildContext: 'docker/Dockerfile.public-frontend'
          

      - task: Docker@2
        displayName: "push public frontend docker image"
        condition: ne(variables['Build.Reason'], 'PullRequest')
        inputs:
          containerRegistry: 'eesdev2'
          repository: 'eesfrontendcontainer'
          command: 'push'
          tags: '${Build.BuildNumber}'


